### ISSUE TITLE
v4.0.1 included breaking changes

### ISSUE THREAD

**Issue by rmg** [crypto-browserify/browserify-sign#34]
CI for most of my projects using browserify started failing within minutes of v4.0.1 being published without any changes to their code.

Looking at the actual v4.0.1 release, it appears to include #25 which changed an interface that many projects use:  [`require('browserify-sign/algos')`](https://github.com/search?p=2&q=browserify-sign%2Falgos&type=Code).

**Comment by rmg** [comment]
I suspect most will be impacted by this breaking crypto-browserify, which is part of browserify itself.

**Comment by calvinmetcalf** [comment]
should be fixed
