### ISSUE TITLE
Error: Can't resolve './browser/algorithms'

### ISSUE THREAD

**Issue by joshunger** [crypto-browserify/browserify-sign#35]
Looks like 4.0.3 was published today.

```
localhost > Module not found: Error: Can't resolve './browser/algorithms' in '.../node_modules/browserify-sign'
localhost > @ ./~/browserify-sign/algos.js 1:17-48
localhost > @ ./~/crypto-browserify/index.js
localhost > @ ./~/node-uuid/uuid.js
```

@calvinmetcalf ?

EDIT: looks like we were missing `.json` in our `extensions: ['.js', '.jsx', '.json']` in our webpack configuration.

**Comment by mohannad-abwah** [comment]
I'm seeing the same problem and can no longer run my Angular2 app. Can we get an ETA for a fix?

**Comment by ajtowf** [comment]
Same here, discovered while recording a pluralsight course, worked hours before the recording :-)

**Comment by ajtowf** [comment]
@mohannad-abwah tmp workaround that worked for me, install 4.0.0 explicitly to your project

**Comment by mohannad-abwah** [comment]
@ajtowf That worked, thanks!

**Comment by kudobyte** [comment]
As @joshunger said, adding `.json` to my webpack config's `resolve: { extensions: [ '.js', '.json' ] }` helped. Thanks!

**Comment by ajtowf** [comment]
@joshunger @kudobyte even better, thanks!

**Comment by antal-bukos** [comment]
Here's an attempt to fix it https://github.com/crypto-browserify/browserify-sign/pull/36

**Comment by abstract-christos** [comment]
Same same, please patch this ASAP! :) thanks

**Comment by ayami123** [comment]
error still the same
`Error: Cannot find module "./browser/algorithms.json"`

**Comment by calvinmetcalf** [comment]
@ayami how are you running this (what build tool) and what version of this do you have ?

**Comment by ayami123** [comment]
I installed npm i CryptoBrowserify
and along came with this.

I use ionic 3 
and for some reason it can't detect .json file ?

**Comment by calvinmetcalf** [comment]
do you know what ionic 3 uses to built it's JS ?
