### ISSUE TITLE
Replace Buffer constructor with Buffer.new()

### ISSUE THREAD

**Issue by gabrielschulhof** [crypto-browserify/browserify-sign#41]
[These places](https://github.com/crypto-browserify/browserify-sign/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) in the code use `new Buffer(...)`. The constructor is deprecated and unsafe. Is it possible to replace those instances with `Buffer.from(...)`?

**Comment by calvinmetcalf** [comment]
yes pull requests accepted to add safe-buffer to this module

**Comment by dcousens** [comment]
See #42 instead
