### ISSUE TITLE
Ignore case in algorithm name

### ISSUE THREAD

**Issue by Fubinator** [crypto-browserify/browserify-sign#71]
I'm currently running into issues with the casing of the `sha256` algorithm name. I'm currently trying to use [react-native-crypto](https://github.com/tradle/react-native-crypto/blob/master/index.js) which users `browserify-sign`. When trying to run `createSign("SHA256")` I get an error, because it's not found in the [algorithms.json](https://github.com/crypto-browserify/browserify-sign/blob/master/browser/algorithms.json) file.

This seems a little bit odd, as in node the case of the algorithm name does not matter. The following is working without any problems in node:

```js
const crypto = require('crypto');

console.log(crypto.createSign('SHA256'));
```

**Comment by calvinmetcalf** [comment]
i think at the time i wrote this algorithm did matter so for the time being you're going to want to lower case it

**Comment by Fubinator** [comment]
All right, thank you for the response.
